version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgree
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: ID
    ports:
      - "8181:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: exampleuser
      DB_PASSWORD: examplepass
      DB_NAME: exampledb
      PORT: 8080
